env:
  global:
    - CC_TEST_REPORTER_ID=eae8b682ab562169f9e44d714d701d9a73566e95450f96c05008cf37a4e19a46
language: ruby
rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - 2.4.10
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - ruby -e "$(curl -s https://undercover-ci.com/uploader.rb)" -- --repo AndyObtiva/easily_typable --commit $TRAVIS_COMMIT --lcov coverage/lcov/easily_typable.lcov
