language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.3
  - 2.1.5
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - ree
gemfile:
  - Gemfile
  - ruby187.Gemfile
matrix:
  exclude:
    - rvm: 2.4.0
      gemfile: ruby187.Gemfile
    - rvm: 2.3.3
      gemfile: ruby187.Gemfile
    - rvm: 2.2.3
      gemfile: ruby187.Gemfile
    - rvm: 2.1.5
      gemfile: ruby187.Gemfile
    - rvm: 2.0.0
      gemfile: ruby187.Gemfile
    - rvm: 1.9.3
      gemfile: ruby187.Gemfile
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: ree
      gemfile: Gemfile
addons:
  code_climate:
    repo_token: 589a0a4a0884844eaa001173
after_success:
  - bundle exec codeclimate-test-reporter
