env:
  global:
    - CC_TEST_REPORTER_ID=eae8b682ab562169f9e44d714d701d9a73566e95450f96c05008cf37a4e19a46
language: ruby
rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - 2.4.10
  - 2.3.8
  - 2.2.10
  - 2.1.5
  - 2.0.0
gemfile:
  - Gemfile
  - ruby187.Gemfile
matrix:
  exclude:
    - rvm: 2.7.1
      gemfile: ruby187.Gemfile
    - rvm: 2.6.6
      gemfile: ruby187.Gemfile
    - rvm: 2.5.8
      gemfile: ruby187.Gemfile
    - rvm: 2.4.10
      gemfile: ruby187.Gemfile
    - rvm: 2.3.8
      gemfile: Gemfile
    - rvm: 2.2.10
      gemfile: Gemfile
    - rvm: 2.1.5
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile
addons:
  code_climate:
    repo_token: eae8b682ab562169f9e44d714d701d9a73566e95450f96c05008cf37a4e19a46
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
