# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: easily_typable 1.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "easily_typable".freeze
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["AndyObtiva".freeze]
  s.date = "2020-05-28"
  s.description = "Ruby mixin that facilitates English-like type checking in an inheritance hierarchy via \"type_name?\" methods".freeze
  s.email = "andy.am@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "lib/easily_typable.rb"
  ]
  s.homepage = "http://github.com/AndyObtiva/easily_typable".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.1.2".freeze
  s.summary = "Ruby mixin that facilitates English-like type checking in an inheritance hierarchy via \"type_name?\" methods".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3.9"])
    s.add_development_dependency(%q<rdoc>.freeze, ["~> 6.2.1"])
    s.add_development_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
    s.add_development_dependency(%q<codeclimate-test-reporter>.freeze, ["~> 1.0.7"])
    s.add_development_dependency(%q<rake>.freeze, ["~> 13.0.1"])
    s.add_development_dependency(%q<rack>.freeze, ["~> 1.6.5"])
    s.add_development_dependency(%q<term-ansicolor>.freeze, ["~> 1.3.2"])
  else
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.9"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 6.2.1"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
    s.add_dependency(%q<codeclimate-test-reporter>.freeze, ["~> 1.0.7"])
    s.add_dependency(%q<rake>.freeze, ["~> 13.0.1"])
    s.add_dependency(%q<rack>.freeze, ["~> 1.6.5"])
    s.add_dependency(%q<term-ansicolor>.freeze, ["~> 1.3.2"])
  end
end

