# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: easily_typable 1.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "easily_typable"
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["AndyObtiva"]
  s.date = "2017-02-08"
  s.description = "Although polymorphism is a recommended standard in Object-Oriented programming for invoking varied behavior in an inheritance hierarchy, sometimes it is still useful to verify if a particular model belongs to a certain type when the behavior concerned does not belong to the model and is too small to require a Design Pattern like Strategy. To avoid the model.is_a?(CertainType) syntax, a more readable approach that developers resort to is to add an English-like method that hides the details of type checking model.certain_type?. Implementing such methods manually gets repetitive after a while, so an easier way to get these methods automatically is to mixin the EasilyTypable module."
  s.email = "andy.am@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "lib/easily_typable.rb"
  ]
  s.homepage = "http://github.com/AndyObtiva/easily_typable"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.8"
  s.summary = "Easier type checking via auto-generated certain_type? methods"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<rdoc>, ["~> 5.0.0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.5.0"])
      s.add_development_dependency(%q<coveralls>, ["= 0.8.5"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.10.0"])
      s.add_development_dependency(%q<codeclimate-test-reporter>, ["~> 1.0.5"])
      s.add_development_dependency(%q<rake>, ["~> 10.4.2"])
      s.add_development_dependency(%q<rack>, ["~> 1.6.5"])
      s.add_development_dependency(%q<nokogiri>, "~> 1.10.4")
      s.add_development_dependency(%q<term-ansicolor>, ["~> 1.3.2"])
    else
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<rdoc>, ["~> 5.0.0"])
      s.add_dependency(%q<rspec>, ["~> 3.5.0"])
      s.add_dependency(%q<coveralls>, ["= 0.8.5"])
      s.add_dependency(%q<simplecov>, ["~> 0.10.0"])
      s.add_dependency(%q<codeclimate-test-reporter>, ["~> 1.0.5"])
      s.add_dependency(%q<rake>, ["~> 10.4.2"])
      s.add_dependency(%q<rack>, ["~> 1.6.5"])
      s.add_dependency(%q<nokogiri>, "~> 1.10.4")
      s.add_dependency(%q<term-ansicolor>, ["~> 1.3.2"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<rdoc>, ["~> 5.0.0"])
    s.add_dependency(%q<rspec>, ["~> 3.5.0"])
    s.add_dependency(%q<coveralls>, ["= 0.8.5"])
    s.add_dependency(%q<simplecov>, ["~> 0.10.0"])
    s.add_dependency(%q<codeclimate-test-reporter>, ["~> 1.0.5"])
    s.add_dependency(%q<rake>, ["~> 10.4.2"])
    s.add_dependency(%q<rack>, ["~> 1.6.5"])
    s.add_dependency(%q<nokogiri>, "~> 1.10.4")
    s.add_dependency(%q<term-ansicolor>, ["~> 1.3.2"])
  end
end

