# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: easily_typable 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "easily_typable".freeze
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["AndyObtiva".freeze]
  s.date = "2017-02-07"
  s.description = "Although polymorphism is a recommended standard in Object-Oriented programming for invoking varied behavior in an inheritance hierarchy, sometimes it is still useful to verify if a particular model belongs to a certain type when the behavior concerned does not belong to the model and is too small to require a Design Pattern like Strategy. To avoid the model.is_a?(CertainType) syntax, a more readable approach that developers resort to is to add an English-like method that hides the details of type checking model.certain_type?. Implementing such methods manually gets repetitive after a while, so an easier way to get these methods automatically is to mixin the EasilyTypable module.".freeze
  s.email = "andy.am@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "lib/easily_typable.rb"
  ]
  s.homepage = "http://github.com/AndyObtiva/easily_typable".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.10".freeze
  s.summary = "Easier type checking via auto-generated certain_type? methods".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3.3"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 5.0.0"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
      s.add_development_dependency(%q<rake>.freeze, ["~> 10.4.2"])
      s.add_development_dependency(%q<rack>.freeze, ["~> 1.6.5"])
      s.add_development_dependency(%q<nokogiri>.freeze, ["~> 1.6.8.1"])
      s.add_development_dependency(%q<tins>.freeze, ["~> 1.6.0"])
      s.add_development_dependency(%q<term-ansicolor>.freeze, ["~> 1.3.2"])
    else
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.3"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 5.0.0"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
      s.add_dependency(%q<rake>.freeze, ["~> 10.4.2"])
      s.add_dependency(%q<rack>.freeze, ["~> 1.6.5"])
      s.add_dependency(%q<nokogiri>.freeze, ["~> 1.6.8.1"])
      s.add_dependency(%q<tins>.freeze, ["~> 1.6.0"])
      s.add_dependency(%q<term-ansicolor>.freeze, ["~> 1.3.2"])
    end
  else
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.3"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 5.0.0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
    s.add_dependency(%q<rake>.freeze, ["~> 10.4.2"])
    s.add_dependency(%q<rack>.freeze, ["~> 1.6.5"])
    s.add_dependency(%q<nokogiri>.freeze, ["~> 1.6.8.1"])
    s.add_dependency(%q<tins>.freeze, ["~> 1.6.0"])
    s.add_dependency(%q<term-ansicolor>.freeze, ["~> 1.3.2"])
  end
end

